#!/usr/bin/env python3
"""Regenerate the four §6 figures (X-1..X-4): resolved year labels + larger fonts.

Year convention (revised 2026-07-08). Figures label every model by its GENERATION
COHORT, not its individual release year; the figure caption states this. So all
earlier-cohort ticks read "(2024)" and all newer-cohort ticks read "(2026)". The two
Mistral-7B ticks were the only ones not already showing their cohort year (they showed
2023); they are fixed here to:
    Mistral-7B (2024)          [2024-cohort member; faithful release Dec 2023 -> prose]
    Mistral-7B (2026 rerun)    [engine bridge: same 2023 weights, generated by us in 2026]
Faithful per-model release years live in the PROSE, not the figures, and span 2023-2026:
earlier cohort is 5/6 genuine 2024 + Mistral-7B (Dec 2023); newer cohort is Mistral-Nemo
(Jul 2024), Gemini-3-Flash / Claude-4.5-Haiku / OLMo-3 / Qwen-3 (2025), GPT-5.4-Mini
(Mar 2026) -- i.e. "2026 cohort" is a generation-year label, not a release year.

Font bumps (2026-07-02; X-1 revised 2026-07-10):
    X-1  +4 everywhere (+2 on 2026-07-02, a further +2 on 2026-07-10)
    X-2  legend +2 (y-labels left as-is; no room)
    X-3  legend +2; right (vocab) panel +2; left y-labels +2 (fig taller to fit)
    X-4  +2 everywhere

X-1 title cut to one line on 2026-07-10 ("Repetition-loop rate by model x topic").
The dropped second line carried a methodological caveat -- that the flagged texts are
degenerate n-gram repetition and are excluded from the length & lexical metrics -- so
that caveat now has to live in the figure CAPTION.

The "Stage 1:" prefix was stripped from all four titles on 2026-07-10 (the stage
numbering is pipeline-internal and means nothing to a chapter reader). First word
re-capitalised in each. The parenthetical qualifiers in X-2 / X-3 are kept: they are
scope statements about which texts the panel is computed over, not stage labels.

Implemented by rebuilding each figure here (calling the pipeline's low-level
helpers) so font sizes can be bumped post-hoc without touching visualize_stage1.py.

Output resolution: DPI below. Font sizes, line widths and marker sizes are all in
POINTS, which matplotlib converts to pixels via the savefig dpi -- so raising DPI
rescales every element together and the layout is byte-for-byte proportional. Only
the pixel grid changes. Set DPI=160 to reproduce the earlier screen-resolution PNGs.

Run:  python3 scripts/figures/regen_figures.py
"""
from pathlib import Path
import sys

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from aiidiolects.paths import REPO_ROOT as PIPE
from aiidiolects import visualize_stage1 as V  # noqa: E402

# --- year labels (earlier cohort; bridge relabelled) ---
FAITHFUL = {
    "phase0_gpt-3.5":       "GPT-3.5\n(2024)",
    "phase0_gpt-4o":        "GPT-4o\n(2024)",
    "phase0_haiku":         "Claude 3.5 Haiku\n(2024)",
    "phase0_llama-3-8b":    "Llama-3\n8B (2024)",
    "phase0_llama-3.1-70b": "Llama-3.1\n70B (2024)",
    "phase0_mistral-7b":    "Mistral-7B\n(2024)",
    "run5_lmstudio":        "Mistral-7B\n(2026 rerun)",
}
V.MODEL_LABELS = {**V.MODEL_LABELS, **FAITHFUL}

# --- colour-blind-safe qualitative palette (Okabe-Ito) ---
V.TOPIC_COLORS = {
    "climate":        "#0072B2",
    "global_warming": "#E69F00",
    "math_anxiety":   "#009E73",
    "misinfo_health": "#CC79A7",
}

DPI = 1200        # publisher requirement (2026-07-10); was 160

CSV = PIPE / "results/phase2_mapping/stage1_descriptives/per_text.csv"
SUMMARY = PIPE / "results/phase2_mapping/stage1_descriptives/summary.csv"
OUT = PIPE / "results" / "chapter_figures"
OUT.mkdir(parents=True, exist_ok=True)


def bump_ax(ax, delta):
    """Increase every text element on an Axes by `delta` points: tick labels,
    heatmap cell annotations, and the (left/centre/right) title + axis labels."""
    for t in (list(ax.get_xticklabels()) + list(ax.get_yticklabels())
              + list(ax.texts)):
        t.set_fontsize(t.get_fontsize() + delta)
    for lbl in (ax.title, getattr(ax, "_left_title", None),
                getattr(ax, "_right_title", None), ax.xaxis.label, ax.yaxis.label):
        if lbl is not None and lbl.get_text():
            lbl.set_fontsize(lbl.get_fontsize() + delta)


def bump_colorbar(cbar, size):
    cbar.ax.yaxis.label.set_fontsize(size)
    cbar.ax.tick_params(labelsize=size)


df = pd.read_csv(CSV)
print(f"rows={len(df):,}  models={sorted(df['model_dir'].unique())}")


def fig_x1(df, out):
    """Repetition-loop rate, model x topic. +4 everywhere; one-line title."""
    m = V._flag_rate_matrix(df, "flag_repetition_loop")
    fig, ax = plt.subplots(figsize=(11, 7))
    im = V.heatmap(ax, m, "", cmap="magma_r", vmin=0, vmax=15,
                   annotate_fmt="{:.1f}")
    cbar = fig.colorbar(im, ax=ax, shrink=0.8,
                        label="% of texts flagged as repetition loop")
    bump_ax(ax, 4)                   # ticks 8->12, cell annotations 7->11
    bump_colorbar(cbar, 14)          # default ~10 -> +4
    fig.suptitle("Repetition-loop rate by model × topic",
                 fontsize=16, y=1.0)  # 12 -> +4
    fig.tight_layout()
    fig.savefig(out, dpi=DPI, bbox_inches="tight")
    plt.close(fig)


def fig_x2(df, out):
    """Length: word count + mean sentence length. Legend +2; axes unchanged.

    Y-axis orientation fix (2026-07-10): boxplot_by_model() calls ax.invert_yaxis()
    internally so position 1 (GPT-3.5, 2024 cohort) sits at the top -- matching
    X-1/X-3/X-4. X-2 is the only figure that calls it TWICE on sharey=True axes, so
    the second invert flips the shared axis back and the two cancel, leaving the 2026
    cohort on top. We force the intended (inverted) orientation explicitly afterwards;
    with sharey it propagates to both panels. Deterministic regardless of invert count."""
    sub = df[V.quality_clean_mask(df, exclude_truncated=True)].copy()
    models = V.order_models(set(sub["model_dir"]))
    fig, axes = plt.subplots(1, 2, figsize=(10.5, 5.5), sharey=True)
    V.boxplot_by_model(axes[0], sub, "n_words",
                       "Word count per text", "words", models)
    V.boxplot_by_model(axes[1], sub, "mean_sent_len",
                       "Mean sentence length", "words / sentence", models)
    axes[1].set_xlim(0, 35)
    # positions are 1..N; (N+0.5 -> 0.5) puts position 1 (GPT-3.5) at the top.
    axes[0].set_ylim(len(models) + 0.5, 0.5)   # sharey -> applies to both panels
    fig.suptitle(
        "Output length and sentence length by model "
        "(quality-clean, non-truncated texts)", fontsize=12, y=1.0)
    fig.legend(handles=V.topic_legend_handles(), loc="lower center", ncol=4,
               frameon=False, fontsize=11, bbox_to_anchor=(0.5, -0.02))  # was 9
    fig.tight_layout(rect=[0, 0.04, 1, 0.97])
    fig.savefig(out, dpi=DPI, bbox_inches="tight")
    plt.close(fig)


def fig_x3(df, out):
    """Lexical diversity: TTR boxplot (left) + vocab heatmap (right, +2). Legend +2.
    Left y-tick (model) labels bumped +2; figure made taller so the 13 two-line
    labels don't overlap (fine to eat into the boxplot width); right
    panel untouched."""
    sub = df[V.quality_clean_mask(df, exclude_truncated=False)].copy()
    models = V.order_models(set(sub["model_dir"]))
    models_heat = V.order_models(set(sub["model_dir"]), for_heatmap=True)
    summary = pd.read_csv(SUMMARY)
    vocab = (summary.pivot(index="model_dir", columns="topic", values="vocab_size")
             .reindex(models_heat).reindex(columns=V.TOPIC_ORDER))
    vals = vocab.values[~np.isnan(vocab.values)]

    fig, axes = plt.subplots(1, 2, figsize=(13, 7.0),
                             gridspec_kw={"width_ratios": [1.4, 1]})
    V.boxplot_by_model(axes[0], sub, "ttr",
                       "Type-token ratio per text", "TTR", models)
    axes[0].set_xlim(0.25, 0.65)
    for t in axes[0].get_yticklabels():      # left model labels only: +2
        t.set_fontsize(t.get_fontsize() + 2)
    im = V.heatmap(axes[1], vocab, "Vocabulary size per (model × topic)",
                   cmap="viridis", vmin=vals.min(), vmax=vals.max(),
                   annotate_fmt="{:.0f}")
    cbar = fig.colorbar(im, ax=axes[1], shrink=0.8, label="unique lemmas")
    bump_ax(axes[1], 2)              # right panel only
    bump_colorbar(cbar, 12)
    fig.suptitle(
        "Lexical diversity (per text) and vocabulary breadth (per group)",
        fontsize=12, y=1.0)
    fig.legend(handles=V.topic_legend_handles(), loc="lower center", ncol=4,
               frameon=False, fontsize=11, bbox_to_anchor=(0.5, -0.02))  # was 9
    fig.tight_layout(rect=[0, 0.04, 1, 0.97])
    fig.savefig(out, dpi=DPI, bbox_inches="tight")
    plt.close(fig)


def fig_x4(df, out):
    """Openers: disclaimer + AI self-reference. +2 everywhere."""
    fig, axes = plt.subplots(1, 2, figsize=(11.5, 6))
    V.heatmap(axes[0], V._flag_rate_matrix(df, "flag_disclaimer"),
              "Disclaimer opener (%)", cmap="magma_r", vmin=0, vmax=100)
    V.heatmap(axes[1], V._flag_rate_matrix(df, "flag_ai_self_ref"),
              "AI self-reference (%)", cmap="magma_r", vmin=0, vmax=100)
    bump_ax(axes[0], 2)
    bump_ax(axes[1], 2)
    fig.suptitle(
        "Opener style is sharply model-specific and topic-conditional",
        fontsize=14, y=1.0)          # was 12 -> +2
    fig.tight_layout(rect=[0, 0.02, 1, 0.97])
    fig.savefig(out, dpi=DPI, bbox_inches="tight")
    plt.close(fig)


fig_x1(df, OUT / "figure_X-1_repetition.png")
fig_x2(df, OUT / "figure_X-2_length.png")
fig_x3(df, OUT / "figure_X-3_lexical_diversity.png")
fig_x4(df, OUT / "figure_X-4_openers_disclaimers.png")
print("wrote 4 figures to", OUT)
